name: PR

on:
    pull_request:
        branches: [develop]

jobs:
    tests:
        name: Build/test on ${{ matrix.name }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    - name: Linux
                      os: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version-file: go.mod
            - name: Vet
              run: go vet ./...
            - name: Build
              run: |
                    go build -v ./...
            - name: start-mongodb
              uses: supercharge/mongodb-github-action@1.12.1
              with:
                mongodb-version: "7.0"
            - name: Test
              env:
                TEST_DB_URI: "mongodb://localhost:27017/unit-tests"
                TEST_COLLECTION: unit-tests
                LOG_LEVEL: DEBUG
              run: |
                    go test -v ./...
